FROM "alpine:3.10"

WORKDIR /home

RUN apk --update --no-cache add  \
        # We stick to Doxygen 1.8.15 (from Alpine 3.10 repo)
        # 1.8.16 in edge repo is bugged (some classes are not documented properly with this version)
        doxygen \

        # Used to generate diagrams
        # We do not forget to include the font (otherwise generated graphs will have squares instead of letters)
        graphviz font-bitstream-type1 \

        # Used to build the PDF using the Makefile generated by Doxygen
        make \

        # Used to convert graphs and images inserted into the PDF
        ghostscript \

        # Main TeX distribution with required dependencies
        texmf-dist \
        texmf-dist-latexextra \
        texmf-dist-langgreek \
        texlive \
        texlive-luatex
